### ISSUE TITLE
Why PureComponent is ignored?

### ISSUE THREAD

**Issue by dangreen** [remcohaszing/babel-plugin-transform-react-class-to-function#1]
**Type**: feature

**OP can fix**: ✔

https://github.com/remcohaszing/babel-plugin-transform-react-class-to-function/blob/master/test/fixtures/bad-import-non-component/output.js#L3

Why PureComponent is ignored?

**Comment by remcohaszing** [comment]
PureComponent is updated in a different way than functional components.

I am willing to accept a PR for this, but then this would need to be an opt-in option.

**Comment by remcohaszing** [comment]
This is now supported by wrapping the component using `React.memo`. :smile:
